[package]
name = "challenge_script"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.34"
shlex = "1.3.0"
thiserror = "2.0.8"
